### ISSUE TITLE
Free-form project support?

### ISSUE THREAD

**Issue by collene** [jonathanlermitage/tikione-jacocoverage#25]
Hi, I was wondering if the plugin will work for Web Free-Form Applications?  I can't seem to find the right click menu options for the plugin on this type of project.  Thanks!

**Comment by jonathanlermitage** [comment]
Hi,
unfortunately, it probably won't work. The plugin needs to know where to
find source files and compiled Java classes in order to perform the code
instrumentation and code coverage.
I know how to discover these files on regular projects, but I have not
implemented support for Free Form projects yet.
I'll try to do it asap.

Regards,
Jonathan

**Comment by jindrapetrik** [comment]
Hi, for Java SE, you can find the compiled classed directories in the block <java-data xmlns="http://www.netbeans.org/ns/freeform-project-java/4"> </java-data>
of nbproject/project.xml file.

See https://github.com/jindrapetrik/jxar/blob/master/nbproject/project.xml  for example

This feature would really help me. Please add it!
I use the free-form projects most of the time.
Thanks in advance!
